apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generator-helm-chart-2.fullname" . }}
  labels:
    app: {{ template "generator-helm-chart-2.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.config.secret | b64enc }}
  {{- $elasticsearch := .Values.config.elasticsearch }}
  elasticsearch_url: {{ $elasticsearch.url | b64enc }}
  elasticsearch_password: {{ $elasticsearch.password | b64enc }}
  {{- $mongodb := .Values.config.mongodb }}
  mongodb_url: {{ $mongodb.url | b64enc }}
  mongodb_password: {{ $mongodb.password | b64enc }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_password: {{ .Values.config.mongoExpress.password | b64enc }}
  {{- end }}
  {{- $mysql := .Values.config.mysql }}
  mysql_url: {{ $mysql.url | b64enc }}
  mysql_password: {{ $mysql.password | b64enc }}
  {{- $postgres := .Values.config.postgres }}
  postgres_url: {{ $postgres.url | b64enc }}
  postgres_password: {{ $postgres.password | b64enc }}
  {{- if .Values.config.pgadmin.enabled }}
  pgadmin_password: {{ .Values.config.pgadmin.password | b64enc }}
  {{- end }}
  {{- $redis := .Values.config.redis }}
  redis_url: {{ $redis.url | b64enc }}
  redis_password: {{ $redis.password | b64enc }}
  {{- if .Values.config.phpredisadmin.enabled }}
  phpredisadmin_password: {{ .Values.config.phpredisadmin.password | b64enc }}
  {{- end }}
